description: Prints a Goodbye greeting message N number of times
implementation:
  container:
    args:
    - --name
    - inputValue: name
    - --iterations
    - inputValue: iterations
    image: gcr.io/
inputs:
- default: World
  description: Bye greeting message to print
  name: name
  type: String
- default: 1
  description: Number of times to print the greeting message
  name: iterations
  type: Integer
name: byeworld
